### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by RufusJWB** [CaliDog/certstream-python#36]
I did install certstream with `$ pip install certstream`

but get the following error when executing it:
```
PS Desktop [09/17/2020 14:31:52]> certstream
Traceback (most recent call last):
  File "C:\Python37\Scripts\certstream-script.py", line 11, in <module>
    load_entry_point('certstream==1.11', 'console_scripts', 'certstream')()
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python37\lib\site-packages\certstream\cli.py", line 8, in <module>
    from signal import signal, SIGPIPE, SIG_DFL
ImportError: cannot import name 'SIGPIPE' from 'signal' (c:\python37\lib\signal.py)
PS Desktop [09/17/2020 14:32:05]>
```
Do you miss a reference?

**Comment by Fitblip** [comment]
Ah yeah I think SIGPIPE support on windows is non-existent (see https://docs.python.org/3/library/signal.html#signal.SIGPIPE). 

Not sure what the fix is since I don't use windows though.
